checking for view messages and view gauges existence
EnvironmentalDashboard/citywide-dashboard-backend pull request #19
Opened 2020-07-15 13:00 UTC by adartulloch

Fixes bug that happened because `ObjectId` that had no view messages returned an empty string, not `[]`. I actually believe that the original code had the right idea and was aware that it needed to return `[]` but just forgot the little check to make sure each field existed in these two ternary expressions.

2020-07-16 21:22 UTC, Sammidysam requested changes
I think we defined `gauges` and `messages` on *all* glyphs, not only views.  Therefore, I think the logic we truly need before the `?` is `result.view && result.view.gauges`.

I think we were just previously assuming all views would have gauges and messages.

2020-07-17 12:28 UTC, adartulloch commented
Oh, I wasn't aware that all glyphs had `gauges` and `messages`.

2020-07-17 14:17 UTC, Sammidysam commented
The route is built for all glyphs (as evidenced by that it is in `glyphs.js` and not `views.js`, though we only populate views with gauges and messages.  It doesn't hurt to make the route work for all glyphs.

2020-07-17 14:17 UTC, Sammidysam commented
I'll do a final test this afternoon.

2020-07-22 19:13 UTC, Sammidysam commented
So sorry about missing this - just tested and merging.

2020-07-22 19:13 UTC, merged